version: '3'
services:
  project2-php-cli:
    extends:
      file: ./../../templates/base.yml
      service: php-cli
    build:
      args:
        PHP_CLI_IMAGE: php:7.4.33-zts-bullseye
  project2-php-fpm:
    extends:
      file: ./../../templates/base.yml
      service: php-fpm
    volumes:
      - ./../:/projects
networks:
  docker_shared_network:
    external: true
